### ISSUE TITLE
Add image upload option with journal post

### ISSUE THREAD

**Issue by Tobibur** [Tobibur/JournalApp#3]
* Add camera option to add image along with the post

* View the post along with the photo if any.

**Comment by jg435dr** [comment]
Hello. I'd like to work on this issue.

**Comment by Tobibur** [comment]
Hi, Sure! PR is welcomed :+1:

**Comment by jg435dr** [comment]
Hi. I want create pull request, but maybe is better if you create next branch.

________________________________
Od: Tobibur Rahman <notifications@github.com>
Odoslané: sobota, 13. októbra 2018 11:18:35
Komu: Tobibur/JournalApp
Kópia: Jakub Grib; Comment
Predmet: Re: [Tobibur/JournalApp] Add image upload option with journal post (#3)


Hi, Sure! PR is welcomed 👍

**Comment by jg435dr** [comment]
Hi. I want create pull request, but maybe is better if you create next branch.

**Comment by Tobibur** [comment]
Do you mean that I should create a new branch? like a development branch?

**Comment by jg435dr** [comment]
Yes. I create pull request to this branch and then if you want you can merge my changes.

**Comment by Tobibur** [comment]
I've created a development branch. Please make your pull request here -> [developement-branch](https://github.com/Tobibur/JournalApp/tree/development)
